# SPDX-FileCopyrightText: 2023-2026 NORCE Research AS
# SPDX-License-Identifier: MIT
# pylint: disable=R0912, R0913, R0914, R0915, R0917

"""Write OPM grid, property, deck, and saturation-function files.

The module serializes COORD and ZCORN geometry, compact keyword arrays, boundary
pore-volume edits, rendered DATA files, and generated saturation tables for the
selected SPE11 configuration.
"""

import os
import subprocess
import sys
from pathlib import Path

import numpy as np
from mako.template import Template
from numpy.typing import NDArray

from pyopmspe11.config.config import Config

HEADER = (
    "-- Copyright (C) 2023-2026 NORCE Research AS\n"
    "-- This deck was generated by pyopmspe11 https://github.com/OPM/pyopmspe11\n"
)


def _calculate_spe11c_z_offset(cfg: Config, y: NDArray) -> NDArray:
    """Calculate SPE11C corner elevations along the y axis.

    Parameters
    ----------
    cfg : Config
        Initialized runtime configuration.
    y : NDArray
        Coordinates along the y axis.

    Returns
    -------
    NDArray
        Calculated numeric values.
    """
    assert cfg.elevation is not None
    dy = cfg.dims[1]
    a = (2.0 * y / dy) - 1.0
    return (
        cfg.maxelevation - cfg.elevation * (1.0 - a * a) - (y * cfg.backElevation / dy)
    )


def _round_significant(v: NDArray) -> NDArray:
    """Round numeric values to eight significant digits.

    Parameters
    ----------
    v : NDArray
        Numeric values to format.

    Returns
    -------
    NDArray
        Calculated numeric values.
    """
    return np.asarray([float(f"{x:E}") for x in v])


def _build_surface_values(
    off: int,
    nx: int,
    ny: int,
    stride_z: int,
    yc: NDArray,
    zcoord: NDArray,
) -> NDArray:
    """Build one rounded ZCORN surface block.

    Parameters
    ----------
    off : int
        Vertical surface offset.
    nx : int
        Number of cells along x.
    ny : int
        Number of cells along y.
    stride_z : int
        Number of pillar points along z.
    yc : NDArray
        SPE11C vertical offsets at y vertices.
    zcoord : NDArray
        Corner-point pillar z coordinates.

    Returns
    -------
    NDArray
        Calculated numeric values.
    """
    zleft = zcoord[off::stride_z][:nx]
    zright = zcoord[off + stride_z :: stride_z][:nx]
    out = [np.empty(0)] * (2 * ny)
    j = 0
    for y in range(ny):
        zb = yc[y]
        zt = yc[y + 1]
        out[j] = np.column_stack((zb + zleft, zb + zright)).ravel()
        out[j + 1] = np.column_stack((zt + zleft, zt + zright)).ravel()
        j += 2
    return _round_significant(np.concatenate(out))


def write_corner_point_grid(
    cfg: Config, xcoord: NDArray, ycoord: NDArray, zcoord: NDArray
) -> None:
    """Write COORD and ZCORN for a corner-point grid.

    Parameters
    ----------
    cfg : Config
        Initialized runtime configuration.
    xcoord : NDArray
        Corner-point pillar x coordinates.
    ycoord : NDArray
        Grid vertices along y.
    zcoord : NDArray
        Corner-point pillar z coordinates.
    """
    grid = []
    top_z = cfg.dims[2]
    nx, ny, nz = cfg.nxyz
    stride_z = nz + 1
    grid.append("COORD\n")
    x_top = xcoord[::stride_z][: nx + 1]
    x_bot = xcoord[nz::stride_z][: nx + 1]
    xx_top, yy = np.meshgrid(x_top, ycoord, indexing="xy")
    xx_bot, _ = np.meshgrid(x_bot, ycoord, indexing="xy")
    vals = np.column_stack(
        (
            xx_top.ravel(),
            yy.ravel(),
            np.zeros(xx_top.size),
            xx_bot.ravel(),
            yy.ravel(),
            np.zeros(xx_top.size),
        )
    ).ravel()
    grid += _format_compact_keyword_values(_round_significant(vals))
    grid.append("/\n")
    grid.append("ZCORN\n")
    if cfg.spe11 == "spe11c":
        yc = _calculate_spe11c_z_offset(cfg, ycoord)
        grid += _format_compact_keyword_values(
            _build_surface_values(0, nx, ny, stride_z, yc, zcoord)
        )
        for k in range(nz - 1):
            blk = _build_surface_values(k + 1, nx, ny, stride_z, yc, zcoord)

            grid += _format_compact_keyword_values(blk)
            grid += _format_compact_keyword_values(blk)
        out = [np.empty(0)] * (2 * ny)
        j = 0
        for y in range(ny):
            zlow = yc[y] + top_z
            zhigh = yc[y + 1] + top_z
            out[j] = np.repeat([zlow, zlow], nx)
            out[j + 1] = np.repeat([zhigh, zhigh], nx)
            j += 2
        grid += _format_compact_keyword_values(_round_significant(np.concatenate(out)))
    else:
        top = np.column_stack(
            (zcoord[0::stride_z][:nx], zcoord[stride_z::stride_z][:nx])
        ).ravel()
        top = _round_significant(top)
        grid += _format_compact_keyword_values(np.concatenate((top, top)))
        for k in range(1, nz):
            zk = np.column_stack(
                (zcoord[k::stride_z][:nx], zcoord[k + stride_z :: stride_z][:nx])
            ).ravel()
            zk = _round_significant(zk)
            if k == nz - 1:
                grid += _format_compact_keyword_values(np.tile(zk, 3))
            else:
                grid += _format_compact_keyword_values(np.tile(zk, 4))
        final_left = zcoord[(np.arange(nx) + 1) * stride_z - 1]
        final_right = zcoord[(np.arange(nx) + 2) * stride_z - 1]
        final = _round_significant(np.column_stack((final_left, final_right)).ravel())
        grid += _format_compact_keyword_values(np.concatenate((zk, final, final)))
    with open(f"{cfg.deckfol}/GRID.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("".join(grid))
        f.write("/\n")


def write_keywords(
    cfg: Config,
    fipnum: NDArray,
    fluxnum: NDArray,
    xmx: NDArray,
    zmz: NDArray | None = None,
    porv: list | None = None,
) -> list[str]:
    """Write grid property include files required by the selected case.

    Parameters
    ----------
    cfg : Config
        Initialized runtime configuration.
    fipnum : NDArray
        FIPNUM values in global cell order.
    fluxnum : NDArray
        Facies identifiers in global cell order.
    xmx : NDArray
        Grid vertices along the x axis.
    zmz : NDArray | None, optional
        Grid vertices along the z axis.
    porv : list | None, optional
        Boundary pore-volume edit records.

    Returns
    -------
    list[str]
        Names of the generated property include files.
    """
    names = []
    if cfg.spe11 == "spe11a":
        if cfg.grid == "tensor":
            assert zmz is not None
            dx = np.tile(xmx[1:] - xmx[:-1], cfg.nxyz[2])
            dz = np.repeat((zmz[1:] - zmz[:-1])[: cfg.nxyz[2]], cfg.nxyz[0])
            _write_keyword(cfg, "DX", dx)
            _write_keyword(cfg, "DZ", dz)
            names.append("DX.INC")
            names.append("DZ.INC")
    elif cfg.spe11 == "spe11b":
        assert porv is not None
        delta_x = xmx[1:] - xmx[:-1]
        if cfg.grid == "tensor":
            assert zmz is not None
            dx = np.tile(delta_x, cfg.nxyz[2])
            dz = np.repeat((zmz[1:] - zmz[:-1])[: cfg.nxyz[2]], cfg.nxyz[0])
            _write_keyword(cfg, "DX", dx)
            _write_keyword(cfg, "DZ", dz)
            names.append("DX.INC")
            names.append("DZ.INC")
        elif np.min(delta_x) != np.max(delta_x) and cfg.grid == "cartesian":
            cfg.compact_dx = True
            dx = np.concatenate(
                [delta_x, np.tile(delta_x[-cfg.nxyz[0] :], cfg.nxyz[2] - 1)]
            )
            _write_keyword(cfg, "DX", dx)
            names.append("DX.INC")
        _write_boundary_pore_volume(cfg, porv)
        names.append("PVBOUNDARIES.INC")
    else:
        assert porv is not None
        _write_boundary_pore_volume(cfg, porv)
    _write_keyword(cfg, "FIPNUM", fipnum)
    _write_keyword(cfg, "FLUXNUM", fluxnum)
    names.append("FIPNUM.INC")
    names.append("FLUXNUM.INC")
    return names


def _write_boundary_pore_volume(cfg: Config, porv: list) -> None:
    """Write boundary pore-volume modifications to an include file.

    Parameters
    ----------
    cfg : Config
        Initialized runtime configuration.
    porv : list
        Boundary pore-volume edit records.
    """
    with open(f"{cfg.deckfol}/PVBOUNDARIES.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("EQUALS\n")
        f.write("\n".join(porv))
        f.write("\n/\n")


def _write_keyword(cfg: Config, name: str, values: NDArray) -> None:
    """Write one numeric OPM keyword to an include file.

    Parameters
    ----------
    cfg : Config
        Initialized runtime configuration.
    name : str
        OPM keyword name.
    values : NDArray
        Numeric keyword values.
    """
    with open(f"{cfg.deckfol}/{name}.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write(f"{name}\n")
        f.write("".join(_format_compact_keyword_values(values)))
        f.write("/\n")


def _format_compact_keyword_values(v: NDArray) -> list:
    """Format numeric values using OPM repeat notation.

    Parameters
    ----------
    v : NDArray
        Numeric values to format.

    Returns
    -------
    list[str]
        Values formatted with OPM repeat notation and trailing separators.
    """
    change = np.concatenate(([True], v[1:] != v[:-1]))
    idx = np.flatnonzero(change)
    counts = np.diff(np.append(idx, v.size))
    uniq = v[idx]
    out = []
    for val, n in zip(uniq, counts):
        if n > 1:
            if val == 0:
                out.append(f"{n}*0 ")
            elif val.is_integer():
                out.append(f"{n}*{int(val)} ")
            else:
                out.append(f"{n}*{val} ")
        else:
            if val == 0:
                out.append("0 ")
            elif val.is_integer():
                out.append(f"{int(val)} ")
            else:
                out.append(f"{val} ")
    return out


def write_opm_input_files(cfg: Config) -> list[str]:
    """Render the main DATA file and saturation-function tables.

    Parameters
    ----------
    cfg : Config
        Initialized runtime configuration.

    Returns
    -------
    list[str]
        Names of the generated DATA file and saturation-table include file.

    Raises
    ------
    subprocess.CalledProcessError
        If an invoked process exits with a nonzero status.
    """
    names = []
    deckfol = Path(cfg.deckfol)
    mytemplate = Template(filename=f"{cfg.pat}/templates/co2/{cfg.spe11}.mako")
    filledtemplate = mytemplate.render(
        nxyz=cfg.nxyz,
        model=cfg.model,
        diffusion=cfg.diffusion,
        dispersion=cfg.dispersion,
        dims=cfg.dims,
        cut=cfg.cut,
        lower=cfg.lower,
        grid=cfg.grid,
        compact_dx=cfg.compact_dx,
        radius=cfg.radius,
        wellijk=cfg.wellijk,
        wellijkf=cfg.wellijkf,
        wellkh=cfg.wellkh,
        rock=cfg.rock,
        kzMult=cfg.kzMult,
        rockCond=cfg.rockCond,
        temperature=cfg.temperature,
        rockExtra=cfg.rockExtra,
        datum=cfg.datum,
        pressure=cfg.pressure,
        maxelevation=cfg.maxelevation,
        spe11aBC=cfg.spe11aBC,
        safu=cfg.safu,
        sensorijk=cfg.sensorijk,
        inj=cfg.inj,
        tuning=cfg.tuning,
        drsdtcon=cfg.drsdtcon,
    )
    filename = Path(cfg.fol).name.upper() + ".DATA"
    filepath = deckfol / filename
    names.append(filename)
    with open(filepath, "w", encoding="utf8") as file:
        file.write(filledtemplate)
    mytemplate = Template(
        filename=f"{cfg.pat}/templates/common/saturation_functions.mako"
    )
    deckfol = Path(cfg.deckfol)
    filledtemplate = mytemplate.render(
        s_w=cfg.s_w,
        krw_expr=cfg.krw,
        krn_expr=cfg.krn,
        pcap_expr=cfg.pcap,
        safu=cfg.safu,
        deckfol=deckfol.as_posix(),
    )
    script = deckfol / "saturation_functions.py"
    with open(script, "w", encoding="utf8") as file:
        file.write(filledtemplate)
    if os.name != "nt":
        subprocess.run(["chmod", "u+x", str(script)], check=True)
    subprocess.run([sys.executable, str(script)], check=True)
    script.unlink(missing_ok=True)
    names.append("TABLES.INC")
    return names


def write_regular_spe11c_grid(
    cfg: Config, xmx: NDArray, ymy: NDArray, zmz: NDArray
) -> None:
    """Write COORD and ZCORN for a structured SPE11C grid.

    Parameters
    ----------
    cfg : Config
        Initialized runtime configuration.
    xmx : NDArray
        Grid vertices along the x axis.
    ymy : NDArray
        Grid vertices along the y axis.
    zmz : NDArray
        Grid vertices along the z axis.
    """
    grid = []
    grid.append("COORD\n")
    xx, yy = np.meshgrid(xmx, ymy, indexing="xy")
    grid += _format_compact_keyword_values(
        _round_significant(
            np.column_stack(
                (
                    xx.ravel(),
                    yy.ravel(),
                    np.zeros(xx.size),
                    xx.ravel(),
                    yy.ravel(),
                    np.zeros(xx.size),
                )
            ).ravel()
        )
    )
    grid.append("/\n")
    grid.append("ZCORN\n")
    nx, ny, nz = cfg.nxyz
    z_base = _calculate_spe11c_z_offset(cfg, ymy)
    out = []
    for y in range(ny):
        zb = z_base[y]
        zt = z_base[y + 1]
        out.append(np.repeat([zb, zb], nx))
        out.append(np.repeat([zt, zt], nx))
    grid += _format_compact_keyword_values(_round_significant(np.concatenate(out)))
    for k in range(nz - 1):
        shift = zmz[k + 1]
        out = []
        for y in range(ny):
            zb = z_base[y] + shift
            zt = z_base[y + 1] + shift
            out.append(np.repeat([zb, zb], nx))
            out.append(np.repeat([zt, zt], nx))
        blk = _round_significant(np.concatenate(out))
        grid += _format_compact_keyword_values(np.tile(blk, 2))
    final_shift = cfg.dims[2]
    out = []
    for y in range(ny):
        zb = z_base[y] + final_shift
        zt = z_base[y + 1] + final_shift
        out.append(np.repeat([zb, zb], nx))
        out.append(np.repeat([zt, zt], nx))
    grid += _format_compact_keyword_values(_round_significant(np.concatenate(out)))
    with open(f"{cfg.deckfol}/GRID.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("".join(grid))
        f.write("/\n")
